# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(383, 134)
        Form.setMinimumSize(QtCore.QSize(383, 95))
        self.sec_k = QtWidgets.QPushButton(Form)
        self.sec_k.setGeometry(QtCore.QRect(270, 10, 101, 31))
        self.sec_k.setObjectName("sec_k")
        self.calistir = QtWidgets.QPushButton(Form)
        self.calistir.setGeometry(QtCore.QRect(270, 50, 101, 31))
        self.calistir.setObjectName("calistir")
        self.kaynak = QtWidgets.QLineEdit(Form)
        self.kaynak.setGeometry(QtCore.QRect(10, 10, 251, 31))
        self.kaynak.setObjectName("kaynak")
        self.sonuc = QtWidgets.QLineEdit(Form)
        self.sonuc.setGeometry(QtCore.QRect(10, 50, 251, 31))
        self.sonuc.setObjectName("sonuc")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(10, 100, 100, 27))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(self.kaynak.clear)
        self.pushButton.clicked.connect(self.sonuc.clear)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.sec_k.setText(_translate("Form", "Seç"))
        self.calistir.setText(_translate("Form", "Çalıştır"))
        self.kaynak.setPlaceholderText(_translate("Form", "dosyayı seç"))
        self.sonuc.setPlaceholderText(_translate("Form", "sonuç dosyasının adı"))
        self.pushButton.setText(_translate("Form", "Temizle"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
