# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1459, 1497)
        Form.setMinimumSize(QtCore.QSize(1395, 1345))
        Form.setMaximumSize(QtCore.QSize(3000, 3000))
        self.pdf_goster = QtWebEngineWidgets.QWebEngineView(Form)
        self.settings().setAttribute(
            QtWebEngineWidgets.QWebEngineSettings.PluginsEnabled, True)
        self.settings().setAttribute(
            QtWebEngineWidgets.QWebEngineSettings.PdfViewerEnabled, True
        )
        self.pdf_goster.setGeometry(QtCore.QRect(20, 0, 1391, 1351))
        self.pdf_goster.setMinimumSize(QtCore.QSize(1351, 1191))
        self.pdf_goster.setMaximumSize(QtCore.QSize(3000, 3000))
        self.pdf_goster.setUrl(QtCore.QUrl("about:blank"))
        self.pdf_goster.setObjectName("pdf_goster")
        
        self.degerler = QtWidgets.QPlainTextEdit(Form)
        self.degerler.setGeometry(QtCore.QRect(860, 1410, 231, 71))
        self.degerler.setMinimumSize(QtCore.QSize(231, 71))
        self.degerler.setMaximumSize(QtCore.QSize(231, 71))
        self.degerler.setObjectName("degerler")
        self.idler = QtWidgets.QPlainTextEdit(Form)
        self.idler.setGeometry(QtCore.QRect(510, 1410, 341, 71))
        self.idler.setMinimumSize(QtCore.QSize(341, 71))
        self.idler.setMaximumSize(QtCore.QSize(341, 71))
        self.idler.setObjectName("idler")
        self.yukle = QtWidgets.QPushButton(Form)
        self.yukle.setGeometry(QtCore.QRect(350, 1410, 131, 71))
        self.yukle.setMinimumSize(QtCore.QSize(131, 71))
        self.yukle.setMaximumSize(QtCore.QSize(131, 71))
        self.yukle.setObjectName("yukle")
        self.dir_path = QtWidgets.QPlainTextEdit(Form)
        self.dir_path.setGeometry(QtCore.QRect(20, 1410, 311, 71))
        self.dir_path.setMinimumSize(QtCore.QSize(311, 71))
        self.dir_path.setMaximumSize(QtCore.QSize(311, 71))
        self.dir_path.setObjectName("dir_path")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(530, 1370, 271, 23))
        self.label.setMinimumSize(QtCore.QSize(271, 23))
        self.label.setMaximumSize(QtCore.QSize(271, 23))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(870, 1370, 271, 23))
        self.label_2.setMinimumSize(QtCore.QSize(271, 23))
        self.label_2.setMaximumSize(QtCore.QSize(271, 23))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(1110, 1390, 251, 23))
        self.label_3.setMinimumSize(QtCore.QSize(251, 23))
        self.label_3.setMaximumSize(QtCore.QSize(251, 23))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(1110, 1420, 251, 23))
        self.label_4.setMinimumSize(QtCore.QSize(251, 23))
        self.label_4.setMaximumSize(QtCore.QSize(251, 23))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(1110, 1450, 251, 23))
        self.label_5.setMinimumSize(QtCore.QSize(251, 23))
        self.label_5.setMaximumSize(QtCore.QSize(251, 23))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(40, 1370, 121, 21))
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.degerler.setPlainText(_translate("Form", "Deger Burada Gozukur"))
        self.idler.setPlainText(_translate("Form", "ID Burada Gozukur"))
        self.yukle.setText(_translate("Form", "Baslat"))
        self.dir_path.setPlainText(_translate("Form", "Dosya Yolunu Ver"))
        self.label.setText(_translate("Form", "ID"))
        self.label_2.setText(_translate("Form", "Deger"))
        self.label_3.setText(_translate("Form", "Ileri Gitmek Icin: D"))
        self.label_4.setText(_translate("Form", "Geri Gitmek Icin: A"))
        self.label_5.setText(_translate("Form", "Kaydet ve Cik: B"))
        self.label_6.setText(_translate("Form", "Dosya Yolu"))
from PyQt5 import QtWebEngineWidgets
